import time
from selenium.webdriver.common.by import By
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from  selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
import random

driver = webdriver.Chrome()
driver.maximize_window()
driver.get('https://swen17-geotech-team-c-frontend.vercel.app/')
element = WebDriverWait(driver,5, 0.5).until(EC.presence_of_element_located((By.XPATH, "/html/body/div[1]/section/section/section/aside/div[1]/ul/li[2]/div/span[1]")))
driver.find_element(By.XPATH, "/html/body/div[1]/section/section/section/aside/div[1]/ul/li[2]/div/span[1]").click()
time.sleep(2)
driver.find_element(By.XPATH, "/html/body/div[1]/section/section/section/aside/div[1]/ul/li[2]/ul/li[2]").click()
time.sleep(2)
driver.execute_script("window.scrollTo(0, 500);")
time.sleep(5)
#generate random inputs:
Nn_max = round(random.uniform(0, 100), 2)
Ns_max = round(random.uniform(0, 100), 2)
Nm_max = round(random.uniform(0, 100), 2)
m = round(random.uniform(0, 100), 2)
n = round(random.uniform(0, 100), 2)
p = round(random.uniform(0, 100), 2)
q = round(random.uniform(0, 100), 2)
Sum = round(random.uniform(0, 100), 2)
k = round(random.uniform(0, 100), 2)
En = round(random.uniform(0, 100), 2)
d = round(random.uniform(0, 100), 2)
Nc = round(random.uniform(0, 100), 2)
μ = round(random.uniform(0, 100), 2)
θm = round(random.uniform(0, 100), 2)
B = round(random.uniform(0, 100), 2)
L = round(random.uniform(0, 100), 2)
en = round(random.uniform(0, 100), 2)
ep = round(random.uniform(0, 100), 2)
input_element = driver.find_element(By.XPATH, "/html/body/div[1]/section/section/section/section/main/div/form/div[1]/div[1]/div[1]/div[2]/div[1]/div/div[2]/div/div/div/div[2]/input")
input_element.send_keys(Keys.CONTROL + "a")
input_element.send_keys(Keys.DELETE)
input_element.send_keys(str(Nn_max))
input_element = driver.find_element(By.XPATH, "/html/body/div[1]/section/section/section/section/main/div/form/div[1]/div[1]/div[1]/div[2]/div[2]/div/div[2]/div/div/div/div[2]/input")
input_element.send_keys(Keys.CONTROL + "a")
input_element.send_keys(Keys.DELETE)
input_element.send_keys(str(Ns_max))
input_element = driver.find_element(By.XPATH, "/html/body/div[1]/section/section/section/section/main/div/form/div[1]/div[1]/div[1]/div[2]/div[3]/div/div[2]/div/div/div/div[2]/input")
input_element.send_keys(Keys.CONTROL + "a")
input_element.send_keys(Keys.DELETE)
input_element.send_keys(str(Nm_max))
input_element = driver.find_element(By.XPATH, "/html/body/div[1]/section/section/section/section/main/div/form/div[1]/div[1]/div[1]/div[2]/div[4]/div/div[2]/div/div/div/div[2]/input")
input_element.send_keys(Keys.CONTROL + "a")
input_element.send_keys(Keys.DELETE)
input_element.send_keys(str(m))
input_element = driver.find_element(By.XPATH, "/html/body/div[1]/section/section/section/section/main/div/form/div[1]/div[1]/div[1]/div[2]/div[5]/div/div[2]/div/div/div/div[2]/input")
input_element.send_keys(Keys.CONTROL + "a")
input_element.send_keys(Keys.DELETE)
input_element.send_keys(str(n))
input_element = driver.find_element(By.XPATH, "/html/body/div[1]/section/section/section/section/main/div/form/div[1]/div[1]/div[1]/div[2]/div[6]/div/div[2]/div/div/div/div[2]/input")
input_element.send_keys(Keys.CONTROL + "a")
input_element.send_keys(Keys.DELETE)
input_element.send_keys(str(p))
input_element = driver.find_element(By.XPATH, "/html/body/div[1]/section/section/section/section/main/div/form/div[1]/div[1]/div[1]/div[2]/div[7]/div/div[2]/div/div/div/div[2]/input")
input_element.send_keys(Keys.CONTROL + "a")
input_element.send_keys(Keys.DELETE)
input_element.send_keys(str(q))
time.sleep(2)
driver.find_element(By.XPATH,"/html/body/div[1]/section/section/section/section/main/div/form/div[2]/div/div/div/div/div/button[1]").click()
time.sleep(20)
driver.close()

